### ISSUE TITLE
license

### ISSUE THREAD

**Issue by ajqlee** [rusty-dev/jenkins-job-builder-pipeline#4]
Hi, I intend to packaging this as a debian package:
    https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851542

However I cannot find any license statement in the source tree. Would you mind to add a license statement even it would be as same as jenkins-job-builder is? :)

Best regards,
-Andrew

**Comment by rusty-dev** [comment]
Added license for both `master` and `stable` branches. Keep in mind that the current distributed version of JJB will only work with `stable` branch.

**Comment by ajqlee** [comment]
Thanks.
