### ISSUE TITLE
Support for job-template

### ISSUE THREAD

**Issue by vills** [rusty-dev/jenkins-job-builder-pipeline#6]
Is there any plans to support not only 'job' type, but also 'job-template'?

Thanks.

**Comment by vills** [comment]
Oh. I realised that template isn't a real job :-). But anyway, job-template with `project-type: pipeline` throws an exception.

JJB have limited support for `project-type: workflow` that work fine with templates. Will use it for now.

Thanks for your code!

**Comment by vills** [comment]
It was an exception caused by not escaped `{` symbol. JJB's exception formatting isn't well in that case.

**Comment by rusty-dev** [comment]
workflow is an obsolete plugin that is now called pipeline and supports more features.
Looks like your problem is resolved then?
